apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: discordbot
      hasuraService: custom
    name: discordbot
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: discordbot
      spec:
        containers:
        - env:
          - name: PRODUCTION
            value: "true"
          - name: DISCORD_TOKEN
            valueFrom:
               secretKeyRef:
                  name: hasura-secrets
                  key: discord.bot_token.key
          - name: CLUSTER_NAME
            value: '{{ cluster.name }}'
          image: hasura/hello-world:latest
          imagePullPolicy: IfNotPresent
          name: app
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
        securityContext: {}
        terminationGracePeriodSeconds: 0
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: discordbot
      hasuraService: custom
    name: discordbot
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: discordbot
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
